// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.2
// source: recommend/data_proxy.proto

package rec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Param struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key    string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value  []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Expire int32  `protobuf:"varint,3,opt,name=expire,proto3" json:"expire,omitempty"`
	Field  string `protobuf:"bytes,4,opt,name=field,proto3" json:"field,omitempty"` //batch_hget时使用的field
	Code   int32  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`  //每个key查询时的错误码
}

func (x *Param) Reset() {
	*x = Param{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_data_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_data_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_recommend_data_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *Param) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Param) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Param) GetExpire() int32 {
	if x != nil {
		return x.Expire
	}
	return 0
}

func (x *Param) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Param) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type DPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TableName  string   `protobuf:"bytes,1,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"` // redis集群id
	Cmd        string   `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	Key        string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`     // 保留扩展 hget hmget 等复杂结构的字段
	Param      []*Param `protobuf:"bytes,4,rep,name=param,proto3" json:"param,omitempty"` //支持 get set setex 的字段
	ReqId      string   `protobuf:"bytes,5,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
	MonitorTag string   `protobuf:"bytes,6,opt,name=monitor_tag,json=monitorTag,proto3" json:"monitor_tag,omitempty"` //支持表维度监控上报
}

func (x *DPRequest) Reset() {
	*x = DPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_data_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DPRequest) ProtoMessage() {}

func (x *DPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_data_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DPRequest.ProtoReflect.Descriptor instead.
func (*DPRequest) Descriptor() ([]byte, []int) {
	return file_recommend_data_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *DPRequest) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *DPRequest) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *DPRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DPRequest) GetParam() []*Param {
	if x != nil {
		return x.Param
	}
	return nil
}

func (x *DPRequest) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

func (x *DPRequest) GetMonitorTag() string {
	if x != nil {
		return x.MonitorTag
	}
	return ""
}

type DPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code  uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Param []*Param `protobuf:"bytes,2,rep,name=param,proto3" json:"param,omitempty"`
	ReqId string   `protobuf:"bytes,3,opt,name=req_id,json=reqId,proto3" json:"req_id,omitempty"`
}

func (x *DPResponse) Reset() {
	*x = DPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_data_proxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DPResponse) ProtoMessage() {}

func (x *DPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_data_proxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DPResponse.ProtoReflect.Descriptor instead.
func (*DPResponse) Descriptor() ([]byte, []int) {
	return file_recommend_data_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *DPResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DPResponse) GetParam() []*Param {
	if x != nil {
		return x.Param
	}
	return nil
}

func (x *DPResponse) GetReqId() string {
	if x != nil {
		return x.ReqId
	}
	return ""
}

var File_recommend_data_proxy_proto protoreflect.FileDescriptor

var file_recommend_data_proxy_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x2f, 0x64, 0x61, 0x74, 0x61,
	0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70,
	0x69, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x22, 0x71, 0x0a, 0x05, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x65, 0x78,
	0x70, 0x69, 0x72, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x22, 0xb2,
	0x01, 0x0a, 0x09, 0x44, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x63,
	0x6d, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x2a, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x2e, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x15, 0x0a, 0x06, 0x72,
	0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x71,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x5f, 0x74, 0x61,
	0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72,
	0x54, 0x61, 0x67, 0x22, 0x63, 0x0a, 0x0a, 0x44, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x2a, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x6d,
	0x6d, 0x65, 0x6e, 0x64, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x05, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x12, 0x15, 0x0a, 0x06, 0x72, 0x65, 0x71, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x72, 0x65, 0x71, 0x49, 0x64, 0x32, 0x54, 0x0a, 0x10, 0x44, 0x61, 0x74, 0x61,
	0x50, 0x72, 0x6f, 0x78, 0x79, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a, 0x07,
	0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x2e, 0x44, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x64, 0x2e, 0x44, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x2f,
	0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x50,
	0x01, 0x5a, 0x1c, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x61, 0x70,
	0x69, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x3b, 0x72, 0x65, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_recommend_data_proxy_proto_rawDescOnce sync.Once
	file_recommend_data_proxy_proto_rawDescData = file_recommend_data_proxy_proto_rawDesc
)

func file_recommend_data_proxy_proto_rawDescGZIP() []byte {
	file_recommend_data_proxy_proto_rawDescOnce.Do(func() {
		file_recommend_data_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_recommend_data_proxy_proto_rawDescData)
	})
	return file_recommend_data_proxy_proto_rawDescData
}

var file_recommend_data_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_recommend_data_proxy_proto_goTypes = []interface{}{
	(*Param)(nil),      // 0: api.recommend.Param
	(*DPRequest)(nil),  // 1: api.recommend.DPRequest
	(*DPResponse)(nil), // 2: api.recommend.DPResponse
}
var file_recommend_data_proxy_proto_depIdxs = []int32{
	0, // 0: api.recommend.DPRequest.param:type_name -> api.recommend.Param
	0, // 1: api.recommend.DPResponse.param:type_name -> api.recommend.Param
	1, // 2: api.recommend.DataProxyService.process:input_type -> api.recommend.DPRequest
	2, // 3: api.recommend.DataProxyService.process:output_type -> api.recommend.DPResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_recommend_data_proxy_proto_init() }
func file_recommend_data_proxy_proto_init() {
	if File_recommend_data_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_recommend_data_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Param); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_data_proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_data_proxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recommend_data_proxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommend_data_proxy_proto_goTypes,
		DependencyIndexes: file_recommend_data_proxy_proto_depIdxs,
		MessageInfos:      file_recommend_data_proxy_proto_msgTypes,
	}.Build()
	File_recommend_data_proxy_proto = out.File
	file_recommend_data_proxy_proto_rawDesc = nil
	file_recommend_data_proxy_proto_goTypes = nil
	file_recommend_data_proxy_proto_depIdxs = nil
}
