// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.17.2
// source: recommend/data_proxy.proto

package rec

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DataProxyServiceClient is the client API for DataProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DataProxyServiceClient interface {
	Process(ctx context.Context, in *DPRequest, opts ...grpc.CallOption) (*DPResponse, error)
}

type dataProxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataProxyServiceClient(cc grpc.ClientConnInterface) DataProxyServiceClient {
	return &dataProxyServiceClient{cc}
}

func (c *dataProxyServiceClient) Process(ctx context.Context, in *DPRequest, opts ...grpc.CallOption) (*DPResponse, error) {
	out := new(DPResponse)
	err := c.cc.Invoke(ctx, "/api.recommend.DataProxyService/process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataProxyServiceServer is the server API for DataProxyService service.
// All implementations must embed UnimplementedDataProxyServiceServer
// for forward compatibility
type DataProxyServiceServer interface {
	Process(context.Context, *DPRequest) (*DPResponse, error)
	mustEmbedUnimplementedDataProxyServiceServer()
}

// UnimplementedDataProxyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedDataProxyServiceServer struct {
}

func (UnimplementedDataProxyServiceServer) Process(context.Context, *DPRequest) (*DPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedDataProxyServiceServer) mustEmbedUnimplementedDataProxyServiceServer() {}

// UnsafeDataProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DataProxyServiceServer will
// result in compilation errors.
type UnsafeDataProxyServiceServer interface {
	mustEmbedUnimplementedDataProxyServiceServer()
}

func RegisterDataProxyServiceServer(s grpc.ServiceRegistrar, srv DataProxyServiceServer) {
	s.RegisterService(&DataProxyService_ServiceDesc, srv)
}

func _DataProxyService_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataProxyServiceServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.recommend.DataProxyService/process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataProxyServiceServer).Process(ctx, req.(*DPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DataProxyService_ServiceDesc is the grpc.ServiceDesc for DataProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DataProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.recommend.DataProxyService",
	HandlerType: (*DataProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "process",
			Handler:    _DataProxyService_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recommend/data_proxy.proto",
}
