// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.2
// source: recommend/histroy_uv.proto

package rec

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IssuedListInfo *HistoryInfo `protobuf:"bytes,1,opt,name=issued_list_info,json=issuedListInfo,proto3" json:"issued_list_info,omitempty"` // 用户的下发历史
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_histroy_uv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_histroy_uv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_recommend_histroy_uv_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetIssuedListInfo() *HistoryInfo {
	if x != nil {
		return x.IssuedListInfo
	}
	return nil
}

type HistoryInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HistoryTermList []*HistoryTerm `protobuf:"bytes,1,rep,name=history_term_list,json=historyTermList,proto3" json:"history_term_list,omitempty"`
}

func (x *HistoryInfo) Reset() {
	*x = HistoryInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_histroy_uv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryInfo) ProtoMessage() {}

func (x *HistoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_histroy_uv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryInfo.ProtoReflect.Descriptor instead.
func (*HistoryInfo) Descriptor() ([]byte, []int) {
	return file_recommend_histroy_uv_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryInfo) GetHistoryTermList() []*HistoryTerm {
	if x != nil {
		return x.HistoryTermList
	}
	return nil
}

type HistoryTerm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId string `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Ts     uint64 `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"` // 下发/曝光 时间戳
}

func (x *HistoryTerm) Reset() {
	*x = HistoryTerm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_recommend_histroy_uv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HistoryTerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryTerm) ProtoMessage() {}

func (x *HistoryTerm) ProtoReflect() protoreflect.Message {
	mi := &file_recommend_histroy_uv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryTerm.ProtoReflect.Descriptor instead.
func (*HistoryTerm) Descriptor() ([]byte, []int) {
	return file_recommend_histroy_uv_proto_rawDescGZIP(), []int{2}
}

func (x *HistoryTerm) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *HistoryTerm) GetTs() uint64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

var File_recommend_histroy_uv_proto protoreflect.FileDescriptor

var file_recommend_histroy_uv_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x2f, 0x68, 0x69, 0x73, 0x74,
	0x72, 0x6f, 0x79, 0x5f, 0x75, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70,
	0x69, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x22, 0x50, 0x0a, 0x08, 0x55,
	0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x44, 0x0a, 0x10, 0x69, 0x73, 0x73, 0x75, 0x65,
	0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x64, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0e, 0x69,
	0x73, 0x73, 0x75, 0x65, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x55, 0x0a,
	0x0b, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x46, 0x0a, 0x11,
	0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x5f, 0x74, 0x65, 0x72, 0x6d, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x72, 0x65,
	0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x2e, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x54,
	0x65, 0x72, 0x6d, 0x52, 0x0f, 0x68, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x54, 0x65, 0x72, 0x6d,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x36, 0x0a, 0x0b, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x54,
	0x65, 0x72, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x74, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x74, 0x73, 0x42, 0x1e, 0x5a, 0x1c,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x72, 0x6f, 0x78, 0x79, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x3b, 0x72, 0x65, 0x63, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_recommend_histroy_uv_proto_rawDescOnce sync.Once
	file_recommend_histroy_uv_proto_rawDescData = file_recommend_histroy_uv_proto_rawDesc
)

func file_recommend_histroy_uv_proto_rawDescGZIP() []byte {
	file_recommend_histroy_uv_proto_rawDescOnce.Do(func() {
		file_recommend_histroy_uv_proto_rawDescData = protoimpl.X.CompressGZIP(file_recommend_histroy_uv_proto_rawDescData)
	})
	return file_recommend_histroy_uv_proto_rawDescData
}

var file_recommend_histroy_uv_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_recommend_histroy_uv_proto_goTypes = []interface{}{
	(*UserInfo)(nil),    // 0: api.recommend.UserInfo
	(*HistoryInfo)(nil), // 1: api.recommend.HistoryInfo
	(*HistoryTerm)(nil), // 2: api.recommend.HistoryTerm
}
var file_recommend_histroy_uv_proto_depIdxs = []int32{
	1, // 0: api.recommend.UserInfo.issued_list_info:type_name -> api.recommend.HistoryInfo
	2, // 1: api.recommend.HistoryInfo.history_term_list:type_name -> api.recommend.HistoryTerm
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_recommend_histroy_uv_proto_init() }
func file_recommend_histroy_uv_proto_init() {
	if File_recommend_histroy_uv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_recommend_histroy_uv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_histroy_uv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistoryInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_recommend_histroy_uv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HistoryTerm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_recommend_histroy_uv_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_recommend_histroy_uv_proto_goTypes,
		DependencyIndexes: file_recommend_histroy_uv_proto_depIdxs,
		MessageInfos:      file_recommend_histroy_uv_proto_msgTypes,
	}.Build()
	File_recommend_histroy_uv_proto = out.File
	file_recommend_histroy_uv_proto_rawDesc = nil
	file_recommend_histroy_uv_proto_goTypes = nil
	file_recommend_histroy_uv_proto_depIdxs = nil
}
